@startuml "Simple API Management Architecture"

!include ./base.puml

title Simple API Management Architecture

' Main components
AzureAPIManagement(apim, "API Management", "")
AzureApplicationInsights(appinsights, "Application Insights", "")
AzureLogAnalyticsWorkspace(loganalytics, "Log Analytics", "")

' Custom components
collections "Apps" as apps #LightBlue
collections "APIs" as apis #LightGreen

' Define the relationships between components
apps --> apim : "API Consumers"
apis -up-> apim : "Deployed to"
apim -right-> appinsights : "\nSends\ntelemetry\n"
appinsights -down-> loganalytics : "Stores telemetry"

@enduml